### ISSUE TITLE
Does anyone know how to solve the bcm94360cs2 network card problem?

### ISSUE THREAD

**Issue by knifead** [johnnynunez/Xiaomi-Mi-Air#264]
Air13.3 8250u mx150 sn550

I unlocked DVMT and cfg, and adjusted related items in config, deleted AirportItlwm, BlueToolFixup, IntelBluetoothFirmware, IntelBluetoothInjector, NVMeFix

I removed the native network card and replaced it with bcm94360cs2. Everything is normal in windows. 
**But in macOS, my Bluetooth will be disconnected as soon as it is connected**. 

  蓝牙控制器：
  地址：	D0:81:7A:C2:66:CD
  状态：	打开
  芯片组：	BCM_20702B0
  可被发现：	关闭
  固件版本：	v150 c9318
  产品ID：	0x0001
  支持的服务：	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  传输：	USB
  供应商ID：	0x004C (Apple)

**Comment by In1t0** [comment]
兄弟你解决了吗？

**Comment by johnnynunez** [comment]
you should change USB kext!
