### ISSUE TITLE
cannot boot in 7.7.9

### ISSUE THREAD

**Issue by Omoinemie** [johnnynunez/Xiaomi-Mi-Air#265]
My laptop is 8250u+mx150，the 7.7.9 Black screen cannot be used at startup1

**Comment by lxc8624** [comment]
so do i. i can't boot opencore either.

**Comment by Lelo5657** [comment]
Try this EFI
https://github.com/Lelo5657/Xiaomi-Mi-Air

**Comment by Lelo5657** [comment]
I think something went wrong in Johnnys Repo by updating it ... there are a lot of files like filename.* and a second file like filename 2.*

**Comment by Lelo5657** [comment]
> so do i. i can't boot opencore either.

did my efi work for u?

**Comment by yaoyuan188** [comment]
> > so do i. i can't boot opencore either.
> 
> did my efi work for u?

Same for me, but the older version 7.7.4 works.

**Comment by Lelo5657** [comment]
Ok - what OS are you using? this EFI is designed for Monterey

**Comment by yaoyuan188** [comment]
> Ok - what OS are you using? this EFI is designed for Monterey

OH NO, I struggled with this on High sierta...

**Comment by Lelo5657** [comment]
in this case you would need other kexts

**Comment by sunls24** [comment]
After closing Secure Boot, you can start normally, modify the oc configuration file `Misc -> Security -> SecureBootModel` to `Disabled`, test in mojave

**Comment by sunls24** [comment]
SecureBootModel is enabled by default in version 7.7.5 and above, only macOS 11+ is supported

**Comment by Yunhao0799** [comment]
I created a fork with fixed EFI

**Comment by Yunhao0799** [comment]
> +

I can only boot with SecureBootModel Disabled with Big Sur
