### ISSUE TITLE
V7.8 boot cannot use builtin keyboard or mouse to choose boot  options

### ISSUE THREAD

**Issue by ahaolee** [johnnynunez/Xiaomi-Mi-Air#277]
Hi johnny , I use V7.8 with MacOS Monterey 12.4 , when i reboot from macos or boot the laptop, when it in boot meun state , my builtin keyboard and mouse cannot working to choose the boot options .Like most people ,  only use the keyboard to select the boot option after  reboot from windows.

**Comment by Lelo5657** [comment]
Is a known issue - there is some problem with the insyde BIOS - happens also th HP Notebooks - you can also press and hold the power button on restart so it "hardresets" and the PS2 keyboard will work again ... there is no fix to this till now

**Comment by johnnynunez** [comment]
updated for ventura
