### ISSUE TITLE
V7.8 wakeup after sleep , bluthooth cause CPU usage  99%+ always

### ISSUE THREAD

**Issue by ahaolee** [johnnynunez/Xiaomi-Mi-Air#278]
Hi  , I use release version 7.8 EFI  ,  and my laptop cpu usage 99%+ after sleep wakeup , cpu temperature rises rapidly . by looking at task monitor , I found that the cpu usage of bluetooth process is 99%+ always , and can't force close bluetooth process , can't close bluetooth on system setting panel .  1/2 probability happens .

**Comment by knifead** [comment]
monterey出现的问题，我降级成big sur就好了

**Comment by johnnynunez** [comment]
try to run script https://github.com/acidanthera/CPUFriend
