### ISSUE TITLE
boot loop after installation

### ISSUE THREAD

**Issue by BigKing33** [johnnynunez/Xiaomi-Mi-Air#280]
after cliking the buttum contine and choosing the ssd drive the process of installation start but after i have a boot loop

**Comment by Ostap1337** [comment]
Hello, I have the same problem. Did you manage to solve it?

**Comment by BigKing33** [comment]
No sorry say me if you solve it please

**Comment by Ostap1337** [comment]
I managed to solve the problem. I put macOS on the second m2 samsung evo 960 and it worked.  On the M2, the one that comes with the laptop is a cyclic reboot at the second stage of the installation.

**Comment by johnnynunez** [comment]
the ssd pm98* it's incompatible with macos
