### ISSUE TITLE
Which bios use?

### ISSUE THREAD

**Issue by tonyelpriulas** [johnnynunez/Xiaomi-Mi-Air#281]
HI, I have recently hackintoshed my TM1703 8250U using this wonderful guide.

Currently I have the XMAKB3M0P1B13 bios and I was wondering if it is necessary or recommended to update it or downgrade it to another version before applying the patches for unlock CFG.

Many thanks in advance for the help

**Comment by johnnynunez** [comment]
exists an google drive with all bios
