### ISSUE TITLE
Stuc on IOPlatformPanicAction -> AppleSMC after the instalation.

### ISSUE THREAD

**Issue by BigKing33** [johnnynunez/Xiaomi-Mi-Air#282]
The installation is clear. I am now boot from the usb but in the opencore menu i chose MacOS (the name of the disk where i install the macOS Monterey). I have a lot of code but at the end i have: 
IOPlatformPanicAction -> AppleSMC after the instalation 
Attempting system restart...
IOPlatformPanicAction -> AppleSMC after the instalation
IOPlatformPanicAction -> AppleSMC after the instalation
Please help.

**Comment by johnnynunez** [comment]
Try ventura
